# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12qsOkfvJHfuynqXxzyHLwOJhOjhamo6D
"""

class StudentDatabase:
    def __init__(self):
        self.students = {}

    def add_student(self, student_id, name, grade):
        self.students[student_id] = {'name': name, 'grade': grade}

    def remove_student(self, student_id):
        if student_id in self.students:
            del self.students[student_id]

    def search_student(self, student_id):
        return self.students.get(student_id, None)

    def display_students(self):
        for student_id, info in self.students.items():
            print(f"Student ID: {student_id}, Name: {info['name']}, Grade: {info['grade']}")

def main():
    database = StudentDatabase()

    while True:
        print("\nStudent Database Menu:")
        print("1. Add Student")
        print("2. Remove Student")
        print("3. Search Student")
        print("4. Display All Students")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            student_id = input("Enter student ID: ")
            name = input("Enter student name: ")
            grade = input("Enter student grade: ")
            database.add_student(student_id, name, grade)
        elif choice == '2':
            student_id = input("Enter student ID to remove: ")
            database.remove_student(student_id)
        elif choice == '3':
            student_id = input("Enter student ID to search: ")
            student = database.search_student(student_id)
            if student:
                print(f"Student ID: {student_id}, Name: {student['name']}, Grade: {student['grade']}")
            else:
                print("Student not found.")
        elif choice == '4':
            database.display_students()
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()
